// step3pt and step3en loaded from backgroundQuestions.js
const data = {
  pt: {
    step1: step1pt,
    step2: step2pt,
    step3: step3pt
  },
  en: {
    step1: step1en,
    step2: step2en,
    step3: step3en,
  }
};
  const speciesInfo = {
    pt: {
    "Aasimar": "Radiantes e de aparência humana, os Aasimar destacam-se pelos olhos brilhantes, traços perfeitos e uma aura que parece sagrada. A sua natureza celestial concede-lhes poderes de cura e a capacidade de invocar explosões de energia divina, por vezes até manifestando asas espectrais.",
    "Dragonborn": "Os Draconatos assemelham-se a dragões bípedes com corpos poderosos, pele escamosa em cores vibrantes e cabeças dracónicas imponentes. Conseguem libertar um sopro de poder elemental—como fogo, relâmpago ou gelo—e são naturalmente resistentes a esse mesmo elemento.",
    "Black Dragonborn": "Os Draconatos têm corpos musculados e escamosos e cabeças reptilianas imponentes. Os Draconatos Negros partilham esta forma mas têm escamas escuras e oleosas e olhos amarelos penetrantes. Cospem ácido e são naturalmente resistentes a ele.",
    "Blue Dragonborn": "Os Draconatos têm corpos musculados e escamosos e cabeças reptilianas imponentes. Os Draconatos Azuis brilham com escamas de cobalto e cristas orgulhosas, respirando relâmpagos e resistindo à sua força.",
    "Brass Dragonborn": "Os Draconatos têm corpos musculados e escamosos e cabeças reptilianas imponentes. Os Draconatos de Latão têm escamas quentes e arenosas e expressões amigáveis, respirando fogo e encantando com facilidade conversadora.",
    "Bronze Dragonborn": "Os Draconatos têm corpos musculados e escamosos e cabeças reptilianas imponentes. Os Draconatos de Bronze cintilam com escamas metálicas de bronze, canalizando relâmpagos com nobreza.",
    "Copper Dragonborn": "Os Draconatos têm corpos musculados e escamosos e cabeças reptilianas imponentes. Os Draconatos de Cobre são cobertos por escamas avermelhadas e douradas, respirando ácido e mostrando um espírito brincalhão.",
    "Gold Dragonborn": "Os Draconatos têm corpos musculados e escamosos e cabeças reptilianas imponentes. Os Draconatos Ouro brilham com escamas douradas e exalam fogo intenso, mantendo uma postura digna e calma.",
    "Green Dragonborn": "Os Draconatos têm corpos musculados e escamosos e cabeças reptilianas imponentes. Os Draconatos Verdes têm escamas verde-esmeralda e olhos astutos, exalando nuvens venenosas que combinam com a sua astúcia.",
    "Red Dragonborn": "Os Draconatos têm corpos musculados e escamosos e cabeças reptilianas imponentes. Os Draconatos Vermelhos brilham com escamas carmesim, libertando chamas ferozes e ambição intensa.",
    "Silver Dragonborn": "Os Draconatos têm corpos musculados e escamosos e cabeças reptilianas imponentes. Os Draconatos de Prata reluzem com escamas prateadas, exalando hálito gelado e protegendo aliados com força tranquila.",
    "White Dragonborn": "Os Draconatos têm corpos musculados e escamosos e cabeças reptilianas imponentes. Os Draconatos Brancos têm escamas brancas como neve e expressões primitivas, respirando frio intenso com instinto puro.",
    "Dwarf": "Baixos, robustos e resistentes, os anões têm barbas espessas, corpos poderosos e olhos firmes. Resistentes a venenos, veem no subsolo e são difíceis de derrubar.",
    "Elf": "Altos e esguios, os elfos têm orelhas alongadas, traços angulosos e uma postura graciosa. Veem na escuridão, resistem a encantamentos e apenas precisam de meditar para descansar.",
    "Drow Elf": "Os elfos são altos e esguios, com orelhas pontiagudas e traços intemporais. Os Elfos Drow partilham esta forma mas têm pele de obsidiana e olhos luminosos, usando magia inata e misturando sedução com perigo.",
    "High Elf": "Os elfos são altos e elegantes, com orelhas longas e postura graciosa. Os Altos Elfos têm traços refinados, tons de pele mais claros e um ar de nobreza. São naturalmente dotados de magia arcana e intelecto aguçado.",
    "Wood Elf": "Os elfos são altos e elegantes, com orelhas longas e postura graciosa. Os Elfos dos Bosques fundem-se nas sombras da floresta com tons terrosos e movimentos silenciosos. São rápidos, furtivos e profundamente ligados à natureza.",
    "Gnome": "Os gnomos são pequenos e enérgicos, com traços exagerados e olhos expressivos. São curiosos e inteligentes, frequentemente resistindo a magias mentais e inventando pequenas maravilhas.",
    "Forest Gnome": "Os gnomos são pequenos e enérgicos, com traços exagerados e olhos expressivos. Os Gnomos da Floresta preferem cores naturais e adornos de folhas, comunicando com animais e escondendo-se com ilusões mágicas.",
    "Rock Gnome": "Os gnomos são pequenos e enérgicos, com traços exagerados e olhos expressivos. Os Gnomos das Rochas transportam ferramentas, lentes e engenhocas, criando dispositivos que realizam pequenos truques mágicos.",
    "Goliath": "Os Golias são enormes e atléticos, mais altos do que a maioria dos mortais. A sua pele é frequentemente pedregosa ou tatuada, e a sua força permite-lhes suportar dores que outros não aguentam.",
    "Cloud Goliath": "Os Golias são humanoides altos e largos, com ascendência elemental. Os Golias das Nuvens têm tez pálida e enevoada e conseguem teletransportar-se brevemente como se montassem o vento.",
    "Fire Goliath": "Os Golias são humanoides altos e largos, com ascendência elemental. Os Golias do Fogo brilham com calor interno, revidando com explosões de fogo quando feridos.",
    "Frost Goliath": "Os Golias são humanoides altos e largos, com ascendência elemental. Os Golias da Geada têm pele azulada e olhos gelados, irradiando frio que abranda os inimigos.",
    "Hill Goliath": "Os Golias são humanoides altos e largos, com ascendência elemental. Os Golias das Colinas são ossudos e corpulentos, derrubando inimigos com pura massa.",
    "Stone Goliath": "Os Golias são humanoides altos e largos, com ascendência elemental. Os Golias de Pedra têm pele cor de ardósia e resistência incomparável a golpes.",
    "Storm Goliath": "Os Golias são humanoides altos e largos, com ascendência elemental. Os Golias da Tempestade crepitam com energia estática, libertando trovões quando são atingidos.",
    "Halfling": "Os Halflings são pequenos e de rosto redondo, com alegria natural e postura humilde. São incrivelmente sortudos, difíceis de apanhar e frequentemente sobrevivem ao perigo com um sorriso.",
    "Human": "Os humanos assemelham-se aos do nosso mundo, mas em D&D são conhecidos pela sua adaptabilidade. Começam com uma vantagem extra, permitindo-lhes sobressair cedo em qualquer papel.",
    "Orc": "Os orcs são altos, musculados e de aparência selvagem, com presas e pele esverdeada ou acinzentada. São brutalmente fortes, podem investir em combate e recuperam mais depressa após serem atingidos.",
    "Tiefling": "Os Tieflings parecem humanos mas com cornos, caudas e pele em tons de vermelho, roxo ou cinzento. A sua ascendência infernal torna-os resistentes a certos feitiços e dá-lhes acesso a poderes mágicos inquietantes.",
    "Abyssal Tiefling": "Os Tieflings são humanoides com cornos, caudas e pele tocada por magia infernal ou demoníaca. Os Abyssal Tieflings têm auras caóticas e olhos demoníacos, resistem a venenos e podem aceder a magias destrutivas.",
    "Chthonic Tiefling": "Os Tieflings são humanoides com cornos, caudas e pele tocada por magia infernal ou demoníaca. Os Chthonic Tieflings têm aspeto pálido e sombrio, resistem a forças necróticas e canalizam poderes dos reinos da morte.",
    "Infernal Tiefling": "Os Tieflings são humanoides com cornos, caudas e pele tocada por magia infernal ou demoníaca. Os Infernal Tieflings têm cornos mais afiados, pele avermelhada e olhos ardentes. Comandam o fogo e suportam punições infernais.",
    "Aarakocra": "Os Aarakocra assemelham-se a aves humanoides com penas, garras e asas que lhes permitem voar desde o início. Os seus corpos ágeis e instintos aviários tornam-nos excelentes batedores, atacantes em mergulho e vigias dos céus.",
    "Bugbear": "Os Bichos-papão são altos, largos e peludos, com traços goblinoides e membros longos. Apesar do tamanho, movem-se com silêncio assustador, atacando das sombras com força bruta e furtividade surpreendente.",
    "Centaur": "Os Centauros combinam a parte superior do corpo humana com a parte inferior de um cavalo poderoso. Rápidos, fortes e majestosos, podem galopar para a batalha, atropelar inimigos e percorrer terrenos selvagens com facilidade.",
    "Changeling": "Os Changelings têm pele pálida e traços suaves em repouso, mas conseguem mudar de rosto e forma à vontade. Mestres do disfarce, transitam entre identidades e adaptam-se a qualquer papel social.",
    "Firbolg": "Os Firbolgs são gigantes gentis com pele azul, cabelo musgoso e olhos profundos que refletem a floresta. Falam com animais e plantas, fundem-se na natureza e usam magia subtil para proteger o bosque.",
    "Githyanki": "Os Githyanki são magros e de pele amarela, com traços longos e olhos penetrantes. Oriundos de reinos astrais, são guerreiros ferozes que atacam com poder psíquico e perícia marcial.",
    "Githzerai": "Os Githzerai partilham o aspeto magro e alongado dos seus parentes Gith mas irradiam calma interior. Mestres da mente sobre a matéria, movem-se com quietude e agem com precisão.",
    "Goblin": "Os Duendes são pequenos, magros e de dentes afiados, com orelhas grandes e dedos ágeis. São rápidos, difíceis de apanhar e recuperam rapidamente após derrotar inimigos.",
    "Hobgoblin": "Os Hobgoblins são goblinoides mais altos e robustos, com pele castanho-avermelhada e postura militar. Lutam em formação, fortalecem aliados e valorizam ordem e honra.",
    "Kobold": "Os Kobolds são pequenos humanoides reptilianos com focinho canino e pele escamosa. Apesar de frágeis, superam inimigos com truques e ganham força lutando em grupo.",
    "Lizardfolk": "Os Lizardfolk são altos e de sangue frio, com peles escamosas, caudas e olhos reptilianos. Mantêm-se calmos sob pressão, fabricam ferramentas de osso e madeira e sobrevivem nos ambientes mais duros.",
    "Minotaur": "Os Minotauros são touros bípedes com torso humanoide, cornos e cascos. Investem com força aterradora, suportam dor e são excelentes rastreadores.",
    "Satyr": "Os Sátiros parecem humanos com pernas de cabra, cornos enrolados e olhos selvagens. O seu charme brincalhão e magia feérica protegem-nos de manipulação e dão-lhes velocidade, ritmo e graça social.",
    "Tabaxi": "Os Tabaxi são felinos humanoides com pelo, cauda, rosto de gato e orelhas inquietas. Ágeis e curiosos, escalam facilmente, escapam ao perigo e perseguem segredos e histórias.",
    "Triton": "Os Tritões são humanoides aquáticos de aspeto régio, com pele escamosa, cristas semelhantes a barbatanas e guelras no pescoço. Respiram debaixo de água, comunicam com criaturas marinhas e usam magia oceânica poderosa.",
    "Tortle": "Os Tortles assemelham-se a tartarugas humanoides com carapaças pesadas, garras e olhos pacientes. A sua carapaça protege-os naturalmente e destacam-se em tarefas de sobrevivência graças à disciplina e sabedoria prática.",
    "Yuan-ti": "Os Yuan-ti são humanoides de pele lisa com olhos de serpente, línguas bifurcadas e, por vezes, escamas subtis. Imunes a venenos e difíceis de manipular, usam magia inquietante para dominar ou assustar.",
    "Deep Gnome": "Os gnomos são pequenos, de cabeças grandes, olhos brilhantes e mãos ocupadas. Os Gnomos das Profundezas são primos subterrâneos com pele cinzenta, olhos grandes e resistência forjada na pedra. Veem na escuridão e escondem-se com magia engenhosa.",
    "Duergar": "Os anões são baixos, robustos e barbudos, com membros sólidos e expressões severas. Os Duergar são os seus parentes cinzentos do Subterrâneo—estoicos, sombrios e dotados de magia que lhes permite crescer ou desaparecer por breves instantes.",
    "Eladrin": "Os elfos são altos, de orelhas longas e postura eterna. Os Eladrin partilham esta graça, mas a sua pele e aura mudam com as estações do Feywild. A sua magia de teletransporte ganha um novo efeito consoante a estação com que o seu espírito se alinha.",
    "Autumn Eladrin": "Os Eladrin são elfos cuja cor e humor mudam com as estações. Os Eladrin Outonais irradiam calor e charme, e quando se teletransportam, os inimigos próximos podem ficar demasiado encantados para retaliar.",
    "Winter Eladrin": "Os Eladrin são elfos cuja cor e humor mudam com as estações. Os Eladrin Invernais são pálidos, distantes e frios como a geada—quando se teletransportam, assustam os inimigos a recuar.",
    "Spring Eladrin": "Os Eladrin são elfos cuja cor e humor mudam com as estações. Os Eladrin Primaveris florescem com energia e bondade, podendo teletransportar outros em vez de si próprios.",
    "Summer Eladrin": "Os Eladrin são elfos cuja cor e humor mudam com as estações. Os Eladrin Estivais brilham com paixão dourada e, ao teletransportarem-se, queimam inimigos à volta com calor radiante.",
    "Fairy": "As Fadas são criaturas do tamanho da palma da mão, com asas delicadas de inseto, pele cintilante e olhos luminosos. Conseguem voar, lançar magia inata e deslumbrar o mundo com uma mistura de fantasia e travessura.",
    "Genasi": "Os Genasi são humanoides infundidos com energia elemental, os seus corpos marcados por características como cabelo eletrificado, pele de pedra, olhos ardentes ou padrões fluidos. Resistentes ao seu elemento, controlam-no com facilidade.",
    "Air Genasi": "Os Genasi exibem traços visuais de magia elemental. Os Genasi do Ar têm cabelo esvoaçante, pele azul-cinzenta e andar leve. Deslizam suavemente, resistem a relâmpagos e movem-se como se fossem levados pelo vento.",
    "Earth Genasi": "Os Genasi exibem traços visuais de magia elemental. Os Genasi da Terra têm pele semelhante a rocha, passos pesados e traços de cristal ou mineral. Mantêm-se firmes, ignoram deslocamentos e terrenos difíceis.",
    "Fire Genasi": "Os Genasi exibem traços visuais de magia elemental. Os Genasi do Fogo irradiam calor, com olhos incandescentes e cabelo de brasa. Suportam chamas e podem invocar luz ardente à vontade.",
    "Water Genasi": "Os Genasi exibem traços visuais de magia elemental. Os Genasi da Água têm pele húmida e brilhante, cabelo cor de algas e movimentos fluidos. Respirando debaixo de água, nadam com graça e moldam água facilmente.",
    "Geppettin (Marionette)": "Os Geppettin assemelham-se a brinquedos vivos—constructos animados com designs distintos. Os Geppettin Marioneta são de madeira e articulados como marionetas, frequentemente com rostos pintados e vozes ocas. Não sentem fome nem fadiga, e muitos destacam-se no teatro ou espionagem.",
    "Geppettin (Plushie or Bisque)": "Os Geppettin assemelham-se a brinquedos vivos—constructos animados com designs distintos. Os Geppettin de Peluche ou Porcelana parecem peluches macios ou bonecas de porcelana animadas. São incansáveis, imortais e evocam conforto e curiosidade.",
    "Marionette Geppettin": "Os Geppettin são brinquedos animados com formas e personalidades distintas. Os Geppettin Marioneta são de madeira, com membros articulados como marionetas e expressões pintadas. São ágeis, expressivos e não precisam de descanso ou alimento.",
    "Bisque Geppettin": "Os Geppettin são brinquedos animados com formas e personalidades distintas. Os Geppettin de Porcelana parecem bonecas de porcelana com traços elegantes e olhos vidrados. São incansáveis e intemporais, muitas vezes graciosos ou inquietantes.",
    "Plushie Geppettin": "Os Geppettin são brinquedos animados com formas e personalidades distintas. Os Geppettin de Peluche são fofos e recheados com olhos de botão e sorrisos costurados. Surpreendentemente resistentes, são acolhedores e estranhos.",
    "Harengon": "Os Harengon são coelhos humanoides com orelhas longas, pernas fortes e energia nervosa. Reagem com velocidade impressionante, saltam grandes distâncias e irradiam curiosidade sem limites.",
    "Kenku": "Os Kenku são humanoides semelhantes a corvos, com corpos emplumados, rostos bicudos e olhos escuros. Falam imitando sons e vozes, sendo mestres da furtividade e memória.",
    "Mandrake": "As Mandrágoras têm pele semelhante a casca, membros folhosos e rostos que mudam com as estações. Sobrevivem à base de luz solar ou carne, enraízam-se para descansar e podem prender inimigos com vinhas vivas.",
    "Spring Mandrake": "As Mandrágoras Primaveris assemelham-se a plantas humanoides com pele de casca e cabelo de folhas. Florescem com verdes frescos e conseguem puxar inimigos voadores para o chão em segurança.",
    "Summer Mandrake": "As Mandrágoras Estivais assemelham-se a plantas humanoides com pele de casca e cabelo de folhas. São densas em folhagem e conseguem empurrar inimigos com vinhas cheias de força.",
    "Autumn Mandrake": "As Mandrágoras Outonais assemelham-se a plantas humanoides com pele de casca e cabelo de folhas. Usam folhas douradas e vermelhas e conseguem prender dois inimigos ao mesmo tempo numa armadilha retorcida.",
    "Winter Mandrake": "As Mandrágoras Invernais assemelham-se a plantas humanoides com pele de casca e cabelo de folhas. São retorcidas e geladas, atacando com vinhas que causam uma explosão de frio.",
    "Sea Elf": "Os Elfos do Mar têm a estrutura esguia e traços afiados dos outros elfos, mas com dedos palmados, guelras e pele em tons marinhos. Respirando e nadando debaixo de água, sentem o apelo do oceano no sangue.",
    "Shadar-kai": "Os Shadar-kai são elfos pálidos, marcados pela sombra e ligados à Rainha dos Corvos. Caminham entre mundos e podem tornar-se insubstanciais por breves instantes, escapando ao perigo com foco sombrio.",
    "Shifter": "Os Metamorfos parecem humanos mas com traços animais—presas, pelo, garras ou olhos brilhantes. Quando mudam, o seu lado animal emerge, desbloqueando habilidades aprimoradas.",
    "Beasthide Shifter": "Os Metamorfos assemelham-se a humanos com traços animais. Os Metamorfos Encouraçados tornam-se mais resistentes ao transformar-se, com pele que se espessa como a de um rinoceronte para suportar golpes.",
    "Longtooth Shifter": "Os Metamorfos assemelham-se a humanos com traços animais. Os Metamorfos Lupinos desenvolvem presas de lobo ao mudar, mordendo ferozmente e avançando para o perigo.",
    "Swiftstride Shifter": "Os Metamorfos assemelham-se a humanos com traços animais. Os Metamorfos Velozes tornam-se esguios e rápidos ao transformar-se, movendo-se entre inimigos com graça felina.",
    "Wildhunt Shifter": "Os Metamorfos assemelham-se a humanos com traços animais. Os Metamorfos Canídeos aguçam os sentidos e instintos, tornando-se quase impossíveis de surpreender e rastreadores perfeitos no seu estado bestial."
    },
    en: {
    "Aasimar": "Radiant and human-like, Aasimar stand out with glowing eyes, flawless features, and an aura that feels holy. Their celestial nature grants them healing powers and the ability to summon bursts of divine energy, sometimes even manifesting spectral wings.",
    "Dragonborn": "Dragonborn look like bipedal dragons with powerful builds, scaled skin in vibrant colours, and imposing draconic heads. They can unleash a breath of elemental power\u2014like fire, lightning, or ice\u2014and naturally shrug off that same element.",
    "Black Dragonborn": "Dragonborn have muscular, scaled bodies and imposing reptilian heads. Black Dragonborn share this form but have dark, oily scales and piercing yellow eyes. They spit acid and are naturally resistant to it.",
    "Blue Dragonborn": "Dragonborn have muscular, scaled bodies and imposing reptilian heads. Blue Dragonborn shimmer with cobalt scales and proud crests, breathing lightning and resisting its force.",
    "Brass Dragonborn": "Dragonborn have muscular, scaled bodies and imposing reptilian heads. Brass Dragonborn have warm, sandy scales and wide, friendly expressions, breathing fire and charming with talkative ease.",
    "Bronze Dragonborn": "Dragonborn have muscular, scaled bodies and imposing reptilian heads. Bronze Dragonborn glimmer with metallic bronze scales, channeling focused lightning with noble resolve.",
    "Copper Dragonborn": "Dragonborn have muscular, scaled bodies and imposing reptilian heads. Copper Dragonborn are covered in bright reddish-gold scales, breathing acid and displaying a trickster spirit.",
    "Gold Dragonborn": "Dragonborn have muscular, scaled bodies and imposing reptilian heads. Gold Dragonborn shine with regal golden scales, exhaling searing fire and carrying themselves with dignified calm.",
    "Green Dragonborn": "Dragonborn have muscular, scaled bodies and imposing reptilian heads. Green Dragonborn have deep emerald scales and narrow, clever eyes, exhaling poison clouds that match their cunning.",
    "Red Dragonborn": "Dragonborn have muscular, scaled bodies and imposing reptilian heads. Red Dragonborn blaze with crimson scales, unleashing ferocious flames and fierce ambition.",
    "Silver Dragonborn": "Dragonborn have muscular, scaled bodies and imposing reptilian heads. Silver Dragonborn gleam with pale silver scales, exhaling icy breath and protecting allies with calm strength.",
    "White Dragonborn": "Dragonborn have muscular, scaled bodies and imposing reptilian heads. White Dragonborn wear snowy scales and primal snarls, breathing freezing cold with raw instinct.",
    "Dwarf": "Short, broad, and rugged, dwarves have thick beards, powerful builds, and steady eyes. They resist poison, see underground, and are hard to push aside.",
    "Elf": "Tall and slender, elves have elongated ears, angular features, and a graceful bearing. They see in darkness, resist charms, and need only meditation to rest.",
    "Drow Elf": "Elves are tall and slender with pointed ears and ageless features. Drow share this form but have obsidian skin and luminous eyes, wielding innate magic and blending allure with danger.",
    "High Elf": "Elves are tall and elegant, with long ears and graceful poise. High Elves have refined features, brighter skin tones, and an air of nobility. They are naturally gifted with arcane magic and sharp intellect.",
    "Wood Elf": "Elves are tall and elegant, with long ears and graceful poise. Wood Elves blend into forest shadows with earthy tones and quiet movement. They're swift, stealthy, and deeply attuned to nature.",
    "Gnome": "Gnomes are small and sprightly, with oversized features and expressive eyes. They\u2019re curious and clever, often resisting mind-affecting magic and inventing surprising little wonders.",
    "Forest Gnome": "Gnomes are small and sprightly, with oversized features and expressive eyes. Forest Gnomes favour natural colours and leafy adornments, speaking to animals and hiding with magical illusion.",
    "Rock Gnome": "Gnomes are small and sprightly, with oversized features and expressive eyes. Rock Gnomes carry tools, lenses, and gadgets wherever they go, crafting devices that perform minor magical tricks.",
    "Goliath": "Goliaths are massive and athletic, standing head and shoulders above most mortals. Their skin is often stony or tattooed, and their strength lets them shake off pain others can\u2019t endure.",
    "Cloud Goliath": "Goliaths are tall, broad-shouldered humanoids with powerful frames and elemental ancestry. Cloud Goliaths have pale, misty complexions and can briefly teleport as if riding the wind.",
    "Fire Goliath": "Goliaths are tall, broad-shouldered humanoids with powerful frames and elemental ancestry. Fire Goliaths glow with internal heat, striking back with bursts of flame when harmed.",
    "Frost Goliath": "Goliaths are tall, broad-shouldered humanoids with powerful frames and elemental ancestry. Frost Goliaths have bluish skin and icy eyes, radiating cold that slows down their enemies.",
    "Hill Goliath": "Goliaths are tall, broad-shouldered humanoids with powerful frames and elemental ancestry. Hill Goliaths are thick-boned and hulking, knocking enemies down with sheer mass.",
    "Stone Goliath": "Goliaths are tall, broad-shouldered humanoids with powerful frames and elemental ancestry. Stone Goliaths have slate-coloured skin and unmatched toughness that shrugs off blows.",
    "Storm Goliath": "Goliaths are tall, broad-shouldered humanoids with powerful frames and elemental ancestry. Storm Goliaths crackle with static energy, releasing thunderclaps when they\u2019re struck.",
    "Halfling": "Halflings are small and round-faced, with a natural cheer and humble posture. They are astonishingly lucky, hard to catch, and often manage to survive danger with a smile.",
    "Human": "Humans resemble those of our own world, but in D&D, they\u2019re known for their sheer adaptability. They start with an extra edge, allowing them to excel early in any role they choose.",
    "Orc": "Orcs are tall, muscular, and savage-looking, with tusks and greenish or gray skin. They\u2019re brutally strong, can charge into battle, and recover faster than most after a hit.",
    "Tiefling": "Tieflings appear mostly human but with horns, tails, and skin in shades of red, purple, or gray. Their infernal ancestry makes them resistant to certain spells and gives them access to unsettling magical powers.",
    "Abyssal Tiefling": "Tieflings are humanoids with horns, tails, and skin touched by infernal or demonic magic. Abyssal Tieflings have chaotic, wild auras and demonic eyes, shrug off poison, and can tap into destructive spells.",
    "Chthonic Tiefling": "Tieflings are humanoids with horns, tails, and skin touched by infernal or demonic magic. Chthonic Tieflings look pale and shadowed, resist necrotic forces, and channel powers from realms of death.",
    "Infernal Tiefling": "Tieflings are humanoids with horns, tails, and skin touched by infernal or demonic magic. Infernal Tieflings have sharper horns, reddish skin, and focused, fiery eyes. They command fire and endure hellish punishment.",
    "Aarakocra": "Aarakocra resemble humanoid birds with feathers, talons, and wings that grant them flight from the start. Their agile frames and avian instincts make them perfect for soaring scouts, diving attackers, and watchers of the skies.",
    "Bugbear": "Bugbears are tall, broad and furry, with goblinoid features and long limbs. Despite their size, they move with eerie silence, striking from shadows with brute force and surprising stealth.",
    "Centaur": "Centaur combine a human upper body with the lower body of a powerful horse. Fast, strong, and majestic, they can gallop into battle, trample foes, and roam wild terrain with ease.",
    "Changeling": "Changelings appear pale and smooth-featured at rest, but can shift their face and form at will. Masters of disguise, they walk between identities and adapt to any social role.",
    "Firbolg": "Firbolgs are gentle giants with blue skin, mossy hair, and deep eyes that reflect the forest. They speak to animals and plants, blend into nature, and wield subtle magic in defence of the wild.",
    "Githyanki": "Githyanki are lean and yellow-skinned, with long features and sharp eyes. Hailing from astral realms, they are fierce warriors who strike with psychic power and martial skill.",
    "Githzerai": "Githzerai share the gaunt, elongated look of their Gith kin but radiate inner calm. Masters of mind over matter, they move with stillness and act with precise control.",
    "Goblin": "Goblins are small, wiry, and sharp-toothed, with large ears and quick fingers. They're fast, hard to pin down, and bounce back after defeating enemies.",
    "Hobgoblin": "Hobgoblins are taller, sturdier goblinoids with red-brown skin and militaristic bearing. They fight in formation, empower allies, and value order and honour.",
    "Kobold": "Kobolds are tiny reptilian humanoids with doglike snouts and scaly skin. Though frail, they outsmart enemies with tricks and gain strength from fighting side by side.",
    "Lizardfolk": "Lizardfolk are tall and cold-blooded, with scaled hides, tails, and reptilian eyes. They remain calm under pressure, craft tools from bone and bark, and endure the harshest environments.",
    "Minotaur": "Minotaurs are bipedal bulls with humanoid torsos, horns, and hooves. They charge headfirst with terrifying power, shake off pain, and excel at tracking prey.",
    "Satyr": "Satyrs look like humans with goat legs, curled horns, and wild eyes. Their playful charm and fey magic protect them from manipulation and give them speed, rhythm, and social grace.",
    "Tabaxi": "Tabaxi are feline humanoids with fur, tails, catlike faces, and twitchy ears. Agile and curious, they climb easily, dart through danger, and chase after secrets and stories.",
    "Triton": "Tritons are regal aquatic humanoids with scaled skin, fin-like crests, and gills on their necks. They breathe underwater, speak to sea creatures, and wield oceanic magic that evokes the might of the deep.",
    "Tortle": "Tortles resemble humanoid turtles with heavy shells, clawed hands, and patient eyes. Their tough exterior shields them naturally, and they thrive in survival tasks thanks to calm discipline and practical wisdom.",
    "Yuan-ti": "Yuan-ti are smooth-skinned humanoids with serpent eyes, forked tongues, and often faint scale patterns. Immune to poison and hard to manipulate, they use unsettling magic to dominate or terrify.",
    "Deep Gnome": "Gnomes are small, big-headed folk with bright eyes and busy hands. Deep Gnomes are subterranean cousins with grey skin, oversized eyes, and grit carved from stone. They see through darkness and hide with clever magic.",
    "Duergar": "Dwarves are short, broad, and bearded, with solid limbs and stern expressions. Duergar are their ashen kin from the Underdark\u2014stoic, grim, and gifted with magic that lets them grow or vanish briefly.",
    "Eladrin": "Elves are tall, long-eared, and eternally poised. Eladrin share this grace, but their skin and aura shift with the seasons of the Feywild. Their teleportation magic gains a new effect depending on the time of year their spirit aligns with.",
    "Autumn Eladrin": "Eladrin are elves whose colour and mood change with the seasons. Autumn Eladrin radiate warmth and charm, and when they teleport, nearby foes may find themselves too enchanted to strike back.",
    "Winter Eladrin": "Eladrin are elves whose colour and mood change with the seasons. Winter Eladrin are pale, distant, and cold as frost\u2014when they teleport, they frighten foes into backing down.",
    "Spring Eladrin": "Eladrin are elves whose colour and mood change with the seasons. Spring Eladrin bloom with new energy and kindness, and can teleport others instead of themselves.",
    "Summer Eladrin": "Eladrin are elves whose colour and mood change with the seasons. Summer Eladrin blaze with golden passion and when they teleport, they burn foes around them with radiant heat.",
    "Fairy": "Fairies are palm-sized fey with delicate insect wings, sparkling skin tones, and luminous eyes. They can fly, cast innate magic, and dazzle the world with a mix of whimsy and mischief.",
    "Genasi": "Genasi are humanoids infused with elemental energy, their bodies marked by features like crackling hair, stone-textured skin, burning eyes, or flowing patterns. They resist their element and command it effortlessly.",
    "Air Genasi": "Genasi bear visual traces of elemental magic. Air Genasi have windswept hair, blue-grey skin, and a breezy gait. They glide lightly and resist lightning, often moving as if lifted by the wind.",
    "Earth Genasi": "Genasi bear visual traces of elemental magic. Earth Genasi have rock-like skin, heavy footsteps, and crystal or mineral features. They stand firm, shrug off displacement, and ignore rough terrain.",
    "Fire Genasi": "Genasi bear visual traces of elemental magic. Fire Genasi flicker with warmth, bearing smouldering eyes and ember-glow hair. They endure flames and can summon burning light at will.",
    "Water Genasi": "Genasi bear visual traces of elemental magic. Water Genasi have wet, glistening skin, seaweed-colored hair, and fluid movements. They breathe underwater, swim with grace, and shape water effortlessly.",
    "Geppettin (Marionette)": "Geppettin resemble living toys\u2014animated constructs with distinct designs. Marionette Geppettin are wooden and jointed like puppets, often with painted faces and hollow-sounding voices. They feel no hunger or fatigue, and many excel in theatre or espionage.",
    "Geppettin (Plushie or Bisque)": "Geppettin resemble living toys\u2014animated constructs with distinct designs. Plushie or Bisque Geppettin resemble soft stuffed animals or porcelain dolls brought to life. They\u2019re tireless, ageless, and evoke both comfort and curiosity.",
    "Marionette Geppettin": "Geppettin are animated toys with distinct forms and personalities. Marionette types are wooden, limbed like puppets, with painted expressions. They\u2019re agile, expressive, and feel no need for rest or food.",
    "Bisque Geppettin": "Geppettin are animated toys with distinct forms and personalities. Bisque Geppettin resemble porcelain dolls with elegant features and glassy eyes. They\u2019re tireless and timeless, often graceful or eerie.",
    "Plushie Geppettin": "Geppettin are animated toys with distinct forms and personalities. Plushie Geppettin are squishy and stuffed, with button eyes and stitched smiles. Surprisingly resilient, they\u2019re cuddly and uncanny.",
    "Harengon": "Harengon are rabbitfolk with long ears, strong legs, and twitchy energy. They react with blinding speed, leap great distances, and often radiate boundless curiosity.",
    "Kenku": "Kenku are crowlike humanoids with feathered bodies, beaked faces, and dark eyes. They speak by mimicking sounds and voices, and are masters of stealth and memory.",
    "Mandrake": "Mandrakes have bark-like skin, leafy limbs, and faces that shift with the seasons. They survive on sunlight or flesh, root in soil to rest, and can entangle enemies with living vines.",
    "Spring Mandrake": "Mandrakes resemble humanoid plants with bark skin and leafy hair. Spring Mandrakes bloom with fresh greens and can pull flying enemies safely to the ground.",
    "Summer Mandrake": "Mandrakes resemble humanoid plants with bark skin and leafy hair. Summer Mandrakes are dense with foliage and can shove enemies aside with vines full of strength.",
    "Autumn Mandrake": "Mandrakes resemble humanoid plants with bark skin and leafy hair. Autumn Mandrakes wear golden-red leaves and can entangle two foes at once in a twisting snare.",
    "Winter Mandrake": "Mandrakes resemble humanoid plants with bark skin and leafy hair. Winter Mandrakes are gnarled and frosted, striking with vines that deal a burst of cold.",
    "Sea Elf": "Sea Elves have the slender frame and sharp features of other elves, but with webbed fingers, gills, and sea-toned skin. They breathe and swim underwater, and feel the call of the ocean in their blood.",
    "Shadar-kai": "Shadar-kai are pale, shadow-marked elves tied to the Raven Queen. They stride between worlds and can briefly become insubstantial, slipping through danger with grim focus.",
    "Shifter": "Shifters look mostly human but carry beast-like features\u2014fangs, fur, claws, or glowing eyes. When they shift, their animal side surges forward, unlocking heightened abilities.",
    "Beasthide Shifter": "Shifters resemble humans with animal traits. Beasthide Shifters grow tougher when they transform, their skin thickening like a rhino\u2019s hide to endure hits others couldn\u2019t.",
    "Longtooth Shifter": "Shifters resemble humans with animal traits. Longtooth Shifters sprout wolf-like fangs when they shift, biting fiercely and charging headlong into danger.",
    "Swiftstride Shifter": "Shifters resemble humans with animal traits. Swiftstride Shifters grow sleek and fast when transformed, darting between foes with feline grace.",
    "Wildhunt Shifter": "Shifters resemble humans with animal traits. Wildhunt Shifters sharpen their senses and instincts, becoming near-impossible to surprise and perfect trackers in their beast state."
    }
  };

  const classInfo = {
    pt: {
      'Barbarian':'O Bárbaro é a força bruta da natureza. Combate com fúria selvagem, ignorando a dor e libertando ataques devastadores. Quando entra em Rage, torna-se mais difícil de ferir e mais poderoso nos seus golpes. Não usa magia, mas compensa com pura resistência e instinto. É ideal para quem quer estar na linha da frente, a levar e causar pancada sem hesitar.',
      'Bard':'O Bardo é um artista mágico — um contador de histórias, músico ou dançarino que inspira aliados e confunde inimigos. Usa magia através da sua arte, seja ela música, poesia ou dança. É extremamente versátil: pode curar, lançar feitiços, manipular emoções e ainda ter talento para lidar com quase qualquer situação fora de combate.',
      'Cleric':'O Clérigo é o canal de poder divino. Serve uma divindade e invoca milagres para curar, proteger ou castigar. É um pilar de suporte, mas também um combatente eficaz quando necessário. Usa armadura e pode ser tão temido como um guerreiro ou tão vital como um curandeiro, dependendo do domínio divino que escolhe seguir.',
      'Druid':'O Druida é o guardião da natureza. Controla os elementos, cura feridas e transforma-se em animais para explorar ou combater. A sua ligação ao mundo natural permite-lhe lançar magias únicas e adaptar-se a qualquer ambiente. É uma excelente escolha para quem gosta de versatilidade mágica e de proteger o equilíbrio do mundo.',
      'Fighter':'O Guerreiro é o mestre das armas. É treinado em todas as formas de combate físico e adapta-se facilmente ao tipo de luta que preferir — seja com espada, arco ou escudo. Não precisa de magia para brilhar, pois compensa com técnica, disciplina e uma incrível capacidade de resistência e ataque constante em batalha.',
      'Monk':'O Monge é um artista marcial que canaliza energia interior para atingir feitos sobre-humanos. Move-se com velocidade, dá golpes precisos e pode desviar-se de ataques com agilidade extrema. Usa o corpo como arma e combina disciplina física com espiritualidade. Ideal para quem quer ser rápido, ágil e surpreendentemente letal.',
      'Paladin':'O Paladino é o guerreiro sagrado. Luta em nome de uma causa justa ou juramento sagrado e combina armas com magia divina. É resistente, curador e implacável contra o mal. A sua presença inspira aliados e mete respeito nos inimigos. É perfeito para quem quer ser um herói protetor com um forte sentido de dever.',
      'Ranger':'O Patrulheiro é o explorador por excelência. Conhece os caminhos da natureza, persegue inimigos com precisão e usa magia simples para se adaptar ao terreno. Pode ter um companheiro animal e é especialista em sobreviver fora das cidades. É ideal para quem quer jogar como caçador, batedor ou guia experiente.',
      'Rogue':'O Ladino é o mestre da discrição e da precisão. Move-se nas sombras, ataca nos pontos fracos e evita armadilhas com facilidade. Usa agilidade e astúcia em vez de força, sendo letal quando apanha os inimigos desprevenidos. Perfeito para quem gosta de ser furtivo, inteligente e mortal com um só golpe.',
      'Sorcerer':'O Feiticeiro é um utilizador de magia nato. O seu poder vem de dentro — seja de uma herança dracónica, caos selvagem ou outra origem mágica. É explosivo, criativo e pode lançar magias poderosas com facilidade, mas com menos variedade do que outras classes mágicas. Ideal para quem gosta de pura força arcana instintiva.',
      'Warlock':'O Bruxo faz pactos com seres misteriosos — fadas, demónios ou entidades cósmicas — em troca de poder. A sua magia é estranha, única e cheia de truques. Usa invocações e pode disparar feitiços com frequência, mesmo com poucos recursos. Ótimo para quem quer um personagem intrigante com ligações sombrias ou místicas.',
      'Wizard':'O Mago é o verdadeiro estudioso da magia. Aprende através de livros e pesquisa, tendo acesso ao maior número de feitiços do jogo. Pode preparar diferentes magias conforme a situação e é um mestre em versatilidade arcana. Embora frágil fisicamente, é um dos conjuradores mais poderosos a longo prazo.'
    },
    en: {
      'Barbarian':'The Barbarian is raw force of nature. Fights with wild fury, ignoring pain and unleashing devastating attacks. When entering Rage, they become harder to hurt and stronger in their strikes. They do not use magic but rely on sheer toughness and instinct. Ideal for those who want to be on the front line, taking and dealing damage without hesitation.',
      'Bard':'The Bard is a magical performer—a storyteller, musician or dancer who inspires allies and confuses enemies. They use magic through art, whether music, poetry or dance. Extremely versatile: can heal, cast spells, sway emotions and handle nearly any situation outside combat.',
      'Cleric':'The Cleric channels divine power. They serve a deity and call miracles to heal, protect or punish. A pillar of support yet an effective fighter when needed. Wearing armor, they can be feared like a warrior or vital like a healer depending on the divine domain followed.',
      'Druid':'The Druid is guardian of nature. They command the elements, heal wounds and transform into animals to explore or fight. Their bond with the natural world lets them cast unique spells and adapt to any environment. A great choice for those who enjoy magical versatility and protecting the world’s balance.',
      'Fighter':'The Fighter is the master of weapons. Trained in every form of physical combat, they adapt easily to any fighting style—sword, bow or shield. They do not need magic to shine, excelling through technique, discipline and an incredible capacity for endurance and constant offense.',
      'Monk':'The Monk is a martial artist who channels inner energy to achieve superhuman feats. Swift and precise, they dodge attacks with extreme agility. Using the body as a weapon, they blend physical discipline with spirituality. Perfect for those seeking speed, agility and surprising lethality.',
      'Paladin':'The Paladin is the holy warrior. Fighting for a righteous cause or sacred oath, they combine weapons with divine magic. Resilient, healing and relentless against evil, their presence inspires allies and commands respect. Ideal for a heroic protector with a strong sense of duty.',
      'Ranger':'The Ranger is the ultimate explorer. They know nature’s paths, track foes accurately and use simple magic to adapt to the terrain. Possibly with an animal companion, they excel at surviving away from cities. Great for players who want to be a hunter, scout or seasoned guide.',
      'Rogue':'The Rogue is master of stealth and precision. Moving in shadows, striking weak spots and disarming traps with ease, they rely on agility and wit rather than strength. Deadly when catching enemies off guard—ideal for stealthy, clever and lethal play.',
      'Sorcerer':'The Sorcerer wields innate magic. Power comes from within—draconic blood, wild chaos or another magical origin. Explosive and creative, they cast powerful spells easily, though with less variety than other casters. Perfect for those who favor raw, instinctive arcane might.',
      'Warlock':'The Warlock makes pacts with mysterious beings—fey, demons or cosmic entities—for power. Their magic is strange, unique and full of tricks. Using invocations, they can fire spells often even with few resources. Great for an intriguing character with dark or mystical ties.',
      'Wizard':'The Wizard is the true scholar of magic. Studying from books and research, they have access to the largest array of spells. They can prepare different magic for each situation and are masters of arcane versatility. Though physically fragile, they become one of the most powerful spellcasters over time.'
    }
  };

  const subclassInfo = {
    pt: {
      'Path of the Berserker': 'Os Bárbaros são o poder físico em forma pura—guerreiros furiosos movidos por emoções primordiais. O Caminho da Ira leva essa ferocidade ao extremo, libertando violência incontrolável em combate e ignorando interferências mentais, tornando-te uma força da natureza aterradora com brutalidade incomparável.',
      'Path of the Wild Heart': 'Os Bárbaros são guerreiros primordiais que canalizam a sua fúria em poder. O Caminho do Coração Selvagem liga-te a espíritos animais, permitindo que enfureças como um urso, águia ou lobo e ganhes garras, asas e sentidos que ecoam os predadores mais selvagens—lutando como uma besta entre homens.',
      'Path of the World Tree': 'Os Bárbaros lutam com raiva primordial, e os que seguem o Caminho da Árvore do Mundo canalizam raízes cósmicas que atravessam os reinos. Estes guerreiros canalizam a energia de Yggdrasil para curar, aumentar o alcance, invocar ramos para prender inimigos e teletransportar-se pelo campo de batalha como um mito vivo.',
      'Path of the Zealot': 'Os Bárbaros canalizam fúria bruta em combate, e os do Caminho do Fanático transformam essa raiva em poder divino. Tornas-te um berserker sagrado, castigando inimigos com ira sagrada, curando pela fé e até desafiando a morte para lutar em nome do teu deus.',
      'Path of the Muscle Wizard': 'Os Bárbaros lutam com força e fúria, e o Caminho do Mago Musculado permite fingir que és um lançador de feitiços—enquanto na verdade pulverizas inimigos com pura força. Intimidas com o teu "poder arcano", lanças "truques" como murros poderosos e conjuras o feitiço supremo: Punho. Não és só forte, és magicamente forte (e ninguém ousa dizer o contrário).',
      'College of Dance': 'Os Bardos são mestres da performance e magia, transformando música e movimento em poder. Os do Colégio da Dança lutam com graça rodopiante, misturando batalha com ballet—deslizando pelo campo de batalha, inspirando aliados a cada pirueta e esquivando-se do perigo ao seu próprio ritmo.',
      'College of Glamour': 'Os Bardos usam música e carisma como armas mágicas, e os do Colégio do Deslumbre especializam-se em encantamentos feéricos. Tornas-te uma lenda viva, deslumbrando inimigos com ilusões e charme enquanto inspiras aliados com a majestade radiante do Feywild.',
      'College of Lore': 'Os Bardos são versáteis e mestres da magia através da música e conhecimento. O Colégio do Conhecimento transforma-te num colecionador de segredos, permitindo aprender qualquer feitiço, cortar ataques inimigos com astúcia e revelar verdades e enganos com cada frase engenhosa.',
      'College of Valor': 'Os Bardos entrelaçam magia e aço em performances heroicas. O Colégio da Bravura permite-te lutar na linha da frente—cantando lendas antigas, atacando com espada e canção, e mudando o rumo da batalha com magia inspiradora e poder marcial.',
      'Life Domain': 'Os Clérigos canalizam poder divino para curar, proteger e castigar em nome da sua divindade. O Domínio da Vida torna-te o curandeiro supremo, potenciando cada feitiço de cura para restaurar mais saúde e permitindo-te ser um farol radiante de resistência e restauração.',
      'Light Domain': 'Os Clérigos são conjuradores divinos que invocam milagres. O Domínio da Luz equipa-te com radiação intensa, permitindo-te atacar inimigos com fogo e expor ameaças ocultas, queimando a escuridão e a falsidade com a fúria do sol.',
      'Trickery Domain': 'Os Clérigos obtêm poder de patronos divinos, e o Domínio da Trapaça favorece a astúcia e a ilusão. Com bênçãos furtivas, magia enganadora e travessuras divinas, tornas-te um trapaceiro sagrado—confundindo inimigos e transformando a graça divina numa ferramenta de caos.',
      'War Domain': 'Os Clérigos usam poder divino ao serviço dos deuses, e os do Domínio da Guerra prosperam em combate. Avanças para a batalha armado de fé, atacando com fúria divina e abençoando aliados com poder justo, tornando-te uma arma viva do teu deus.',
      'Circle of the Land': 'Os Druidas moldam o mundo com a magia da natureza, e os do Círculo da Terra tornam-se guardiões de lugares antigos. Retiras força de florestas, desertos e tundras, lançando feitiços poderosos e canalizando a energia elemental da terra sob os teus pés.',
      'Circle of the Moon': 'Os Druidas comandam o selvagem, e o Círculo da Lua desbloqueia a tua besta interior. Transformas-te em criaturas temíveis, mudando de forma em combate, aguentando golpes e dilacerando inimigos como um avatar primordial da natureza.',
      'Circle of the Sea': 'Os Druidas canalizam a força da natureza, e o Círculo do Mar controla o poder bruto dos oceanos. Conjuras tempestades, avanças com energia das marés e atacas como uma onda viva—comandando as profundezas para esmagar os inimigos com fúria aquática.',
      'Circle of Stars': 'Os Druidas moldam magia do mundo natural, e o Círculo das Estrelas alcança os céus. Usas padrões celestes para guiar o destino, transformas-te em formas radiantes e lanças magia estrelada que dobra o destino à tua vontade.',
      'Battle Master': 'Os Guerreiros são mestres do combate em todas as formas, e os Mestres de Batalha elevam isso a uma arte. Com manobras experientes e superioridade tática, controlas o campo de batalha, desarmas inimigos, fazes tropeçar adversários e guias aliados como um general veterano.',
      'Champion': 'Os Guerreiros dominam o combate marcial, e os Campeões ultrapassam os limites físicos além do humano. Atacas com mais força, acertas golpes críticos com mais frequência e tornas-te um símbolo de poder heroico puro que domina qualquer arena.',
      'Eldritch Knight': 'Os Guerreiros prosperam no combate corpo a corpo, e o Místico funde proeza marcial com magia arcana. Teleportas-te pelo campo, encantas a tua lâmina e lanças fogo e força juntamente com a espada—usando magia como uma arma.',
      'Psi Warrior': 'Os Guerreiros são peritos táticos, e os Psiónicos afiam a mente como arma. Com empurrões telecinéticos, ataques psíquicos e defesas mentais, tornas-te um monge guerreiro da mente, dobrando a realidade e os inimigos com pura força de vontade.',
      'Dungeoneer': 'Os Guerreiros são mestres da batalha, e o Explorador de Masmorras transforma cada exploração numa vitória tática. Com instintos supersticiosos, reflexos para evitar armadilhas e bónus para descobrir segredos de monstros, tornas-te um guia vivo de sobrevivência e caça ao tesouro—explorando onde outros não ousam e vivendo para contar.',
      'Way of Mercy': 'Os Monges canalizam paz interior e golpes mortais, e a Técnica da Misericórdia caminha entre curandeiro e executor. Com um toque, podes curar feridas ou infligir dor—movendo-te como um agente mascarado de equilíbrio, julgamento e restauração.',
      'Way of Shadow': 'Os Monges movem-se com velocidade e precisão, e os da Técnica da Sombra misturam habilidade marcial com furtividade sobrenatural. Atacas das sombras, desapareces em fumo e tornas-te a personificação do medo e silêncio.',
      'Way of the Elements': 'Os Monges dominam o corpo como arma, e a Técnica dos Elementos permite-te controlar fogo, água, ar e terra com o teu ki. Libertarás fúria elemental com socos, conjurando rajadas de fogo, chicotes de água e mais a cada golpe.',
      'Way of the Open Hand': 'Os Monges aperfeiçoam as artes marciais numa força da natureza, e a Técnica da Mão Aberta é a forma mais pura de mestria desarmada. Derrubas inimigos, empurras adversários e atacas com precisão cirúrgica—intocável e imparável.',
      'Warrior of the Street': 'Os Monges canalizam força interior em perfeição física, e o Lutador das Ruas combate com combos rápidos e movimentos especiais dignos de videojogo. Atiras inimigos ao ar, lanças rajadas de energia e desferes uppercuts imparáveis—transformando cada combate num espetáculo de estilo e perícia.',
      'Oath of Devotion': 'Os Paladinos são campeões divinos ligados a juramentos sagrados. O Juramento da Devoção prende-te a ideais de justiça, honra e luz—permitindo-te castigar o mal com força radiante e proteger os inocentes com determinação inabalável.',
      'Oath of Glory': 'Os Paladinos usam poder sagrado em combate, e o Juramento da Glória transforma-te num paradigma de heroísmo. Inspiras aliados com feitos épicos, avanças como um campeão mítico e encarnas a centelha divina da grandeza lendária.',
      'Oath of the Ancients': 'Os Paladinos são cruzados armados por uma causa maior, e o Juramento dos Ancestrais liga-te à beleza da natureza e alegria. Usas energia radiante para proteger aliados, resistir à escuridão e preservar a vida com poder feérico.',
      'Oath of Vengeance': 'Os Paladinos cumprem votos sagrados, e o Juramento da Vingança jura perseguição implacável dos malfeitores. Caças os ímpios com fúria sobrenatural, acorrentando inimigos, teletransportando-te pelo campo de batalha e tornando-te a mão imparável da retribuição.',
      'Oath of Revelry': 'Os Paladinos são guerreiros divinos ligados a votos sagrados, e os do Juramento da Celebração dedicam-se à alegria, camaradagem e festa sem fim. Conjuras bebidas encantadas, festejas apesar da dor e inspiras aliados com a tua celebração contagiante—lutando pelo direito sagrado de festejar.',
      'Beast Master': 'Os Patrulheiros misturam proeza marcial com magia da natureza, e os Mestres das Feras ligam-se a um companheiro primal. Tu e a tua besta lutam como um só—coordenando ataques, protegendo-se mutuamente e libertando fúria selvagem em harmonia com a natureza.',
      'Fey Wanderer': 'Os Patrulheiros sobrevivem onde outros temem, e os Viajantes Feéricos trazem a beleza caótica do Feywild consigo. Com encantos, lâminas psíquicas e explosões de alegria estranha, moves-te como um cavaleiro trapaceiro entre dois mundos.',
      'Gloom Stalker': 'Os Patrulheiros são caçadores peritos, e os Viajantes das Sombras prosperam na escuridão. Atacas sem ser visto, moves-te como um fantasma pelo Subterrâneo ou noite e destróis inimigos antes que saibam que estás lá.',
      'Hunter': 'Os Patrulheiros protegem a natureza e eliminam ameaças com precisão cirúrgica. Como Caçador, adaptas as tuas habilidades para destruir a presa escolhida—disparando flechas, esquivando ataques e controlando o campo de batalha com eficiência implacável.',
      'Arcane Trickster': 'Os Ladinos são mestres da furtividade e precisão, e o Trapaceiro Arcano adiciona magia ao seu arsenal. Misturas ilusões e encantamentos com ataques furtivos—desarmando armadilhas, desaparecendo à vista e superando inimigos com astúcia arcana.',
      'Assassin': 'Os Ladinos são exímios em emboscada e fuga, e os Assassinos aperfeiçoam a arte da morte. Atacas das sombras com precisão letal, infliges dano massivo a inimigos surpreendidos e moves-te pelo mundo como um fantasma com o toque de uma adaga.',
      'Soulknife': 'Os Ladinos operam nas margens, e os da Lâmina Psíquica usam energia psiónica para se tornarem assassinos mentais. Manifestas lâminas do pensamento, saltas entre mentes e matas com precisão silenciosa—sem depender de aço ou sombra.',
      'Thief': 'Os Ladinos atravessam defesas como fumo, e os Ladrões elevam a infiltração a uma arte. Escalas paredes, desarmas armadilhas, abres fechaduras num instante e roubas tesouros antes que alguém repare—verdadeiros mestres da velocidade e subtileza.',
      'Arachnoid Stalker': 'Os Ladinos prosperam nas sombras, e o Predador Aracnídeo usa poderes de aranha para escalar paredes, lançar teias e envenenar presas. Quer rastejes pelo teto, ataques de cima ou paralises inimigos com veneno, és uma mistura aterradora de furtividade, precisão e agilidade aracnídea.',
      'Aberrant Sorcery': 'Os Feiticeiros usam magia que nasce da sua essência, e os da Magia Aberrante são moldados por poderes alienígenas. Libertam força psiónica, desenvolvem habilidades bizarras e distorcem a realidade—canalizando uma mutação mágica aterradora.',
      'Clockwork Sorcery': 'Os Feiticeiros moldam magia por talento inato, e os da Magia Mecânica personificam a ordem universal. Estabilizas o caos, proteges aliados com timing perfeito e invocas energia tão precisa como um mecanismo cósmico.',
      'Draconic Sorcery': 'Os Feiticeiros têm magia no sangue, e a Magia Dracónica provém do poder ancestral dos dragões. Cresces escamas, resistes a forças elementais e libertas rajadas devastadoras—tornando-te realeza dracónica em forma humana.',
      'Wild Magic': 'Os Feiticeiros lançam feitiços pela força de vontade, e a Magia Caótica é imprevisível. Libertam surtos mágicos que podem mudar o rumo—ou a mesa—em algo maravilhoso, aterrador ou simplesmente bizarro.',
      'Archfey Patron': 'Os Bruxos canalizam poder de patronos de outros mundos, e os ligados ao Arqui-feérico obtêm magia de maravilha e terror. Encantas e confundes com truques feéricos, teletransportas-te numa névoa e usas glamour que dobra mentes e realidade.',
      'Celestial Patron': 'Os Bruxos fazem pactos por poder, e os que servem um Patrono Celestial trazem luz em vez de trevas. Curas com energia radiante, proteges aliados e queimas inimigos com fogo divino—canalizando estrelas e luz estelar pela tua alma.',
      'Fiend Patron': 'Os Bruxos fazem pactos com entidades poderosas, e o Patrono Infernal oferece poder flamejante em troca. Lançam chamas, absorvem vida de inimigos derrotados e comandam magia infernal com cada maldição e bola de fogo.',
      'Great Old One Patron': 'Os Bruxos obtêm poder de fontes insondáveis, e o Patrono Grande Ancião oferece loucura em troca de poder. Lês pensamentos, falas nas mentes e enlouqueces inimigos—canalizando o horror incompreensível do cosmos.',
      'Future You': 'Os Bruxos fazem pactos com poderes estranhos, e o teu é a tua própria versão futura. Com conhecimento do que está para vir, manipulas o destino, controlas o tempo, esquivas ataques que "já sabias que vinham" e infliges dano psíquico com paradoxos—desvendando um destino só teu.',
      'Abjurer': 'Os Magos dominam o conhecimento arcano pelo estudo, e os Abjuradores especializam-se em defesa mágica. Erguem escudos, banem ameaças e tornam-se fortalezas ambulantes—transformando feitiços em muralhas e proteções para aliados.',
      'Diviner': 'Os Magos moldam a realidade com feitiços, e os Divinadores dobram o tempo e o destino. Antecipam o futuro, manipulam resultados com dados proféticos e estão sempre no sítio certo com conhecimento sobrenatural.',
      'Evoker': 'Os Magos comandam força arcana pura, e os Evocadores moldam-na em destruição. Esculpem bolas de fogo, relâmpagos e explosões trovejantes—libertando devastação elemental com controlo absoluto.',
      'Illusionist': 'Os Magos reescrevem a perceção, e os Ilusionistas são mestres do engano. Criam imagens tão reais que enganam dragões, desaparecem nas próprias ilusões e manipulam crenças tão facilmente como a realidade.'
      },
    en: {
      'Path of the Berserker': 'Barbarians are raw physical power given form\u2014raging warriors fueled by primal emotion. The Path of the Berserker takes that ferocity to the next level, unleashing uncontrollable violence in battle and shrugging off mental interference, turning you into a terrifying force of nature with unmatched brutality.',
      'Path of the Wild Heart': 'Barbarians are primal warriors who channel their rage into power. The Path of the Wild Heart bonds you with animal spirits, letting you rage like a bear, eagle, or wolf and grow claws, wings, and senses that echo the wildest predators\u2014fighting as a beast among men.',
      'Path of the World Tree': "Barbarians fight with primal rage, and those who follow the Path of the World Tree tap into cosmic roots that span realms. These warriors channel Yggdrasil's energy to heal, extend their reach, summon branches to trap foes, and teleport across the battlefield like a living myth.",
      'Path of the Zealot': 'Barbarians channel raw fury into combat, and those on the Path of the Zealot turn that rage into divine power. You become a sacred berserker, smiting foes with holy wrath, healing through faith, and even defying death to fight on in your god\u2019s name.',
      'Path of the Muscle Wizard': "Barbarians fight with raw strength and fury, and the Path of the Muscle Wizard lets you pretend you\'re a spellcaster\u2014while actually pulverizing foes with sheer force. You intimidate with your \'arcane prowess\', hurl \'cantrips\' as powerful punches, and cast the ultimate spell: Fist. You\'re not just strong, you\'re magically strong (and no one dares say otherwise).",
      'College of Dance': 'Bards are masters of performance and magic, turning music and motion into power. Bards from the College of Dance fight with swirling grace, blending battle with ballet\u2014darting across the battlefield, inspiring allies with every spin, and dodging danger in a rhythm all their own.',
      'College of Glamour': 'Bards wield music and charisma as magical weapons, and those in the College of Glamour specialize in fey enchantment. You become a living legend, dazzling foes with illusions and charm while inspiring allies with the radiant majesty of the Feywild.',
      'College of Lore': 'Bards are jacks-of-all-trades and masters of magic through music and knowledge. The College of Lore turns you into a collector of secrets, letting you learn any spell, cut through enemy attacks with sharp wit, and reveal truth and trickery with every clever line.',
      'College of Valor': 'Bards weave spell and steel into heroic performances. The College of Valor empowers you to fight on the frontlines\u2014singing of ancient legends, striking foes with sword and song, and turning the tide of battle with inspirational magic and martial might.',
      'Life Domain': 'Clerics channel divine power to heal, protect, and smite in the name of their deity. The Life Domain turns you into the ultimate healer, empowering every healing spell you cast to restore more health and let you act as a radiant beacon of endurance and restoration.',
      'Light Domain': 'Clerics are divine spellcasters who call down miracles. The Light Domain arms you with searing radiance, letting you blast enemies with fire and expose hidden threats, burning away darkness and falsehoods with the fury of the sun.',
      'Trickery Domain': 'Clerics draw power from divine patrons, and the Trickery Domain favors cleverness and illusion. With stealthy blessings, deceptive magic, and divine mischief, you become a holy trickster\u2014confounding foes and turning divine grace into a tool of chaos.',
      'War Domain': 'Clerics wield divine power in service of the gods, and those of the War Domain thrive in battle. You charge into the fray armored in faith, striking with divine fury and blessing your allies with righteous might, becoming a living weapon of your god.',
      'Circle of the Land': 'Druids shape the world with nature\u2019s magic, and those of the Circle of the Land become guardians of ancient places. You draw strength from forests, deserts, and tundras, casting powerful spells and channeling the raw elemental energy of the earth beneath your feet.',
      'Circle of the Moon': 'Druids command the wild, and the Circle of the Moon unlocks your inner beast. You transform into fearsome creatures, shifting shape mid-battle, tanking blows and tearing into foes as a primal avatar of the wilderness.',
      'Circle of the Sea': 'Druids channel nature\u2019s force, and the Circle of the Sea wields the raw power of oceans. You conjure storms, surge with tidal energy, and strike like a living wave\u2014commanding the deep to crush your enemies with aquatic fury.',
      'Circle of Stars': 'Druids shape magic from the natural world, and the Circle of the Stars reaches for the heavens. You harness celestial patterns to guide fate, shift into radiant forms, and cast starlit magic that bends destiny to your will.',
      'Battle Master': 'Fighters are masters of combat in all forms, and Battle Masters elevate that to an art form. With expert maneuvers and tactical superiority, you control the battlefield, disarm enemies, trip foes, and guide your allies like a war-hardened general.',
      'Champion': 'Fighters dominate in martial combat, and Champions push their physical limits beyond mortal bounds. You strike harder, land critical hits more often, and become a symbol of raw, heroic power that dominates any arena of battle.',
      'Eldritch Knight': 'Fighters thrive in close combat, and the Eldritch Knight fuses martial prowess with arcane magic. You blink across the field, enchant your blade, and throw fire and force alongside your sword\u2014wielding magic like a weapon in its own right.',
      'Psi Warrior': 'Fighters are tactical experts, and Psi Warriors sharpen their minds into weapons. With telekinetic shoves, psychic strikes, and mental defenses, you become a warrior monk of the mind, bending reality and your enemies with sheer willpower.',
      Dungeoneer: 'Fighters are masters of battle, and the Dungeoneer turns every dungeon crawl into a tactical triumph. With superstitious instincts, trap-dodging reflexes, and bonuses for uncovering monsters\u2019 secrets, you become a living guidebook of survival and treasure-hunting\u2014delving where others dare not tread and living to boast about it.',
      'Way of Mercy': 'Monks channel inner peace and deadly strikes, and the Way of Mercy walks the fine line between healer and executioner. With a touch, you can mend wounds or inflict pain\u2014moving as a masked agent of balance, judgment, and restoration.',
      'Way of Shadow': 'Monks move with unmatched speed and precision, and those who follow the Way of Shadow blend martial skill with supernatural stealth. You strike from darkness, vanish into smoke, and become a living embodiment of fear and silence.',
      'Way of the Elements': 'Monks master their body as a weapon, and the Way of the Four Elements lets you harness fire, water, air, and earth with your ki. You unleash elemental fury with punches, conjuring fire blasts, water whips, and more with every strike.',
      'Way of the Open Hand': 'Monks perfect martial arts into a graceful force of nature, and the Way of the Open Hand is the purest form of unarmed mastery. You knock enemies down, push them back, and strike with pressure-point precision\u2014untouchable and unstoppable.',
      'Warrior of the Street': 'Monks channel inner strength into physical perfection, and Warriors of the Street throw down with blinding combos and special moves straight out of a fighting game. You knock foes into the air, fire energy blasts, and unleash unstoppable uppercuts\u2014turning every encounter into a highlight reel of style and skill.',
      'Oath of Devotion': 'Paladins are divine champions sworn to uphold sacred oaths. The Oath of Devotion binds you to ideals of justice, honor, and light\u2014empowering you to smite evil with radiant force and protect the innocent with unshakable resolve.',
      'Oath of Glory': 'Paladins wield holy power in battle, and the Oath of Glory turns you into a paragon of heroism. You inspire allies with epic feats, charge into combat like a mythic champion, and embody the divine spark of legendary greatness.',
      'Oath of the Ancients': 'Paladins are armored crusaders for a higher cause, and the Oath of the Ancients roots you in the beauty of nature and joy. You wield radiant energy to shield allies, resist darkness, and preserve life with fey-touched might.',
      'Oath of Vengeance': 'Paladins uphold sacred vows, and the Oath of Vengeance swears relentless pursuit of evildoers. You hunt down the wicked with supernatural fury, chaining foes, teleporting across the battlefield, and becoming the unstoppable hand of retribution.',
      'Oath of Revelry': 'Paladins are divine warriors sworn to sacred vows, and those who swear the Oath of Revelry are devoted to joy, camaraderie, and nonstop celebration. You conjure enchanted drinks, party through pain, and inspire allies to greatness with your infectious revelry\u2014fighting for the sacred right to party.',
      'Beast Master': 'Rangers blend martial prowess with nature magic, and Beast Masters bond with a primal companion. You and your beast fight as one\u2014coordinating attacks, watching each other\u2019s backs, and unleashing wild fury together in harmony with the wilderness.',
      'Fey Wanderer': 'Rangers survive where others fear to tread, and Fey Wanderers bring the chaotic beauty of the Feywild with them. With charms, psychic blades, and bursts of eerie joy, you move like a trickster knight straddling two worlds.',
      'Gloom Stalker': 'Rangers are expert hunters, and Gloom Stalkers thrive in darkness. You strike unseen from the shadows, move like a ghost through the Underdark or night, and destroy your foes before they even know you\'re there.',
      Hunter: 'Rangers protect nature and slay threats with surgical precision. As a Hunter, you tailor your skills to destroy your chosen prey\u2014hailing arrows, dodging blows, and controlling the battlefield with relentless efficiency.',
      'Arcane Trickster': 'Rogues are masters of stealth and precision, and the Arcane Trickster adds magical flair to your bag of tricks. You blend illusions and enchantments with sneak attacks\u2014disarming traps, vanishing in plain sight, and outsmarting foes with arcane guile.',
      Assassin: 'Rogues excel at ambush and escape, and Assassins perfect the art of the kill. You strike from the shadows with lethal timing, deal massive damage to surprised foes, and move through the world as a ghost with a dagger\'s kiss.',
      Soulknife: 'Rogues operate in the margins, and Soulknives harness psionic energy to become psychic killers. You manifest blades from thought, leap between minds, and slay with silent precision\u2014untethered from steel or shadow.',
      Thief: 'Rogues slip through defenses like smoke, and Thieves elevate infiltration to an art. You climb walls, disable traps, pick locks in a blink, and swipe treasures before anyone notices\u2014true masters of speed and subtlety.',
      'Arachnoid Stalker': 'Rogues thrive in the shadows, and the Arachnoid Stalker uses spider-like powers to climb walls, sling webs, and poison prey. Whether crawling across ceilings, ambushing from above, or paralyzing foes with venom, you\'re a terrifying blend of stealth, precision, and arachnid agility.',
      'Aberrant Sorcery': 'Sorcerers wield magic born from their very essence, and Aberrant Sorcerers are shaped by alien powers. You unleash psionic force, grow bizarre abilities, and twist reality itself\u2014channeling a terrifying mutation of magic.',
      'Clockwork Sorcery': 'Sorcerers shape magic through innate talent, and Clockwork Sorcerers embody universal order. You stabilize chaos, protect allies with perfect timing, and summon energy as precise as a ticking cosmic engine.',
      'Draconic Sorcery': 'Sorcerers wield magic in their blood, and Draconic Sorcery draws from a dragon\u2019s ancient power. You grow scales, resist elemental forces, and unleash devastating breath-like blasts\u2014becoming draconic royalty in human form.',
      'Wild Magic': 'Sorcerers cast spells by force of will, and Wild Magic is chaotic and unpredictable. You unleash magic surges that can turn the tide\u2014or the table\u2014into something wondrous, terrifying, or downright bizarre.',
      'Archfey Patron': 'Warlocks channel power from otherworldly patrons, and those bound to the Archfey gain magic rooted in wonder and terror. You charm and confuse with fey tricks, teleport in a swirl of mist, and wield glamour that bends minds and reality.',
      'Celestial Patron': 'Warlocks make pacts for power, and those who serve a Celestial bring light instead of darkness. You heal with radiant energy, shield allies from harm, and burn enemies with divine fire\u2014channeling stars and starlight through your soul.',
      'Fiend Patron': 'Warlocks deal with powerful entities, and the Fiend offers fiery might in return. You hurl flames, absorb life from defeated foes, and command infernal magic with every curse you whisper and fireball you conjure.',
      'Great Old One Patron': 'Warlocks gain power from unfathomable sources, and the Great Old One offers madness in exchange for might. You read thoughts, speak into minds, and drive foes insane\u2014channeling the unknowable horror of the cosmos.',
      'Future You': 'Warlocks make deals with strange powers, and yours is your own time-traveling future self. With knowledge of what\u2019s to come, you bend fate, manipulate time, dodge attacks you "knew were coming", and inflict psychic damage with paradoxes\u2014unfolding a destiny only you truly understand.',
      Abjurer: 'Wizards master arcane knowledge through study, and Abjurers specialize in magical defense. You erect shields, banish threats, and become a walking fortress\u2014turning spells into walls and wards that protect allies and repel foes.',
      Diviner: 'Wizards shape reality with spells, and Diviners bend time and fate. You peer into the future, manipulate outcomes with prophetic dice, and always seem to be in the right place with uncanny foreknowledge.',
      Evoker: 'Wizards command pure arcane force, and Evokers shape it into raw destruction. You sculpt fireballs, lightning bolts, and thunderous blasts\u2014unleashing elemental devastation with pinpoint control.',
      Illusionist: 'Wizards rewrite perception itself, and Illusionists are masters of deception. You create images so real they can fool dragons, vanish into your own illusions, and manipulate belief as easily as reality.'
    }
  };

  const backgroundInfo = {
    pt: {
      'Acolyte':'Foste criado num templo, a servir uma divindade com devoção. Passaste os teus dias a estudar escrituras e a ajudar nas cerimónias. Tens uma forte ligação espiritual e um conhecimento profundo da fé, além de pequenos poderes sagrados aprendidos com os clérigos que te ensinaram.',
      'Artisan':'Cresceste num ambiente de trabalho manual, aprendendo um ofício desde jovem. Sabes como construir, reparar e vender os teus produtos. O teu olho treinado para os detalhes e o jeito com clientes fazem de ti alguém respeitado no mundo do comércio e da criação.',
      'Charlatan':'És um mestre da mentira e da ilusão. Vendeste poções falsas, fingiste ser alguém que não eras ou criaste documentos falsos com um sorriso convincente. Vives da tua lábia, da tua criatividade e de saberes sempre quando fugir.',
      'Criminal':'A tua vida começou nos becos e sombras da cidade. Foste ladrão, arrombador ou espião — talvez sozinho, talvez parte de um gangue. Sabes como mover-te sem ser visto e como escapar de quem te quer apanhar.',
      'Entertainer':'Viveste de aplausos e de fazer o público sorrir. Foste músico, acrobata, poeta ou palhaço. Sabes como cativar uma multidão e tens talento para o espectáculo, sempre pronto a brilhar ou a provocar gargalhadas.',
      'Farmer':'Nasceste e cresceste a trabalhar a terra. Aprendeste o valor do trabalho duro, da paciência e da ligação com os ciclos da natureza. A tua força e resistência vêm de anos de vida simples e esforço contínuo.',
      'Guard':'Serviste como guarda — de uma cidade, de uma muralha ou de um nobre. Estás sempre atento, preparado para intervir quando há perigo. A tua experiência ensinou-te a distinguir problemas ao longe e a manter a calma em situações tensas.',
      'Guide':'Viveste longe da civilização, a explorar florestas, montanhas e ruínas esquecidas. Levas outros por caminhos perigosos com sabedoria e discrição. Conheces os sons da natureza e os perigos que se escondem no meio dela.',
      'Hermit':'Passaste anos em isolamento, a meditar, estudar ou fugir do mundo. A tua mente está habituada à introspeção e ao silêncio. Talvez tenhas encontrado respostas... ou perguntas mais profundas ainda.',
      'Merchant':'Aprendeste a arte da negociação, da logística e do lucro. Vendeste bens por cidades e estradas, conhecendo culturas diferentes e as suas necessidades. És um viajante esperto com olho para oportunidades.',
      'Noble':'Foste criado no luxo de uma casa aristocrática. Aprendeste etiqueta, política e o peso do nome da tua família. Podes ser arrogante ou humilde, mas sabes como se comportar entre poderosos — ou manipulá-los.',
      'Sage':'Desde cedo te fascinaste com o conhecimento. Passaste anos entre livros, pergaminhos e mestres, a tentar compreender o mundo. Tens uma mente afiada e uma curiosidade insaciável, sempre à procura de respostas.',
      'Sailor':'A tua casa foi o mar. Navegaste por águas calmas e tempestades, conhecendo portos distantes e histórias fantásticas. És resistente, adaptável e habituado a uma vida onde tudo pode mudar com o vento.',
      'Scribe':'Trabalhaste a copiar textos importantes, seja em monastérios ou escritórios do governo. Escreves com precisão e atenção ao detalhe. O teu mundo é feito de palavras e de saber preservá-las sem erro.',
      'Soldier':'Foste treinado para a guerra. A tua vida foi feita de disciplina, treino e combate real. Estás habituado ao barulho da batalha, ao peso da armadura e às ordens que não se discutem. És leal, prático e determinado.',
      'Wayfarer':'Cresceste nas ruas, a sobreviver com engenho e teimosia. Aprendeste a mover-te sem ser notado e a confiar apenas em quem merece. Mesmo quando roubaste para sobreviver, nunca perdeste a esperança de um futuro melhor.'
    },
    en: {
      'Acolyte':'You were raised in a temple, serving a deity with devotion. You spent your days studying scriptures and helping in ceremonies. You have a strong spiritual bond and deep knowledge of faith, plus minor holy powers learned from the clerics who taught you.',
      'Artisan':'You grew up in a craftsman\'s environment, learning a trade from a young age. You can build, repair and sell your goods. Your trained eye for detail and skill with customers make you respected in the world of commerce and creation.',
      'Charlatan':'You are a master of lies and illusion. You sold fake potions, pretended to be someone else or forged documents with a convincing smile. You live by your wit, creativity and knowing when to run.',
      'Criminal':'Your life began in the city\'s alleys and shadows. You were a thief, burglar or spy—maybe alone, maybe part of a gang. You know how to move unseen and how to escape those who want to catch you.',
      'Entertainer':'You lived off applause and making the public smile. You were a musician, acrobat, poet or clown. You know how to captivate a crowd and have talent for showmanship, always ready to shine or provoke laughter.',
      'Farmer':'You were born and raised working the land. You learned the value of hard work, patience and the connection with nature\'s cycles. Your strength and endurance come from years of simple life and continuous effort.',
      'Guard':'You served as a guard—for a city, a wall or a noble. Always watchful, ready to intervene when danger arises. Your experience taught you to spot trouble from afar and keep calm in tense situations.',
      'Guide':'You lived far from civilization, exploring forests, mountains and forgotten ruins. You lead others through dangerous paths with wisdom and discretion. You know nature\'s sounds and the dangers hiding within.',
      'Hermit':'You spent years in isolation, meditating, studying or hiding from the world. Your mind is used to introspection and silence. Perhaps you found answers... or deeper questions.',
      'Merchant':'You learned the art of negotiation, logistics and profit. You sold goods along roads and cities, learning different cultures and their needs. You\'re a savvy traveler with an eye for opportunities.',
      'Noble':'You were raised in the luxury of an aristocratic house. You learned etiquette, politics and the weight of your family name. You may be arrogant or humble, but you know how to behave among the powerful—or manipulate them.',
      'Sage':'Fascinated by knowledge from early on, you spent years among books, scrolls and mentors trying to understand the world. You have a sharp mind and insatiable curiosity, always seeking answers.',
      'Sailor':'The sea was your home. You sailed through calm waters and storms, seeing distant ports and fantastic tales. You\'re resilient, adaptable and used to a life where everything can change with the wind.',
      'Scribe':'You worked copying important texts, whether in monasteries or government offices. You write with precision and attention to detail. Your world is made of words and knowing how to preserve them without error.',
      'Soldier':'You were trained for war. Your life was built on discipline, training and real combat. You\'re used to the noise of battle, the weight of armor and orders that are not questioned. Loyal, practical and determined.',
      'Wayfarer':'You grew up on the streets, surviving with cunning and stubbornness. You learned to move unnoticed and to trust only those who deserve it. Even when you stole to survive, you never lost hope for a better future.'
    }
  };

  const labels = {
    pt: { Species:'Espécie', Class:'Classe', Style:'Estilo de Jogo', Background:'Antecedente', restart:'Recomeçar' },
    en: { Species:'Species', Class:'Class', Style:'Playing Style', Background:'Background', restart:'Restart Quiz' }
  };

const miscText = {
  pt: {
    noResults: 'Sem resultados disponíveis.',
    seeMore: 'Ver mais',
    language: 'Idioma:',
    notChosen: 'Por escolher',
    quizTitle: 'Questionário de Personagem de D&D',
    resultsTitle: 'Resultados do Questionário',
    promptIntro: 'Cola este prompt num gerador de arte IA para visualizares a tua personagem!'
  },
  en: {
    noResults: 'No results available.',
    seeMore: 'See more',
    language: 'Language:',
    notChosen: 'Yet to be chosen',
    quizTitle: 'D&D Character Quiz',
    resultsTitle: 'Quiz Results',
    promptIntro: 'Paste this prompt into an AI art generator to visualize your character!'
  }
};

const startText = {
  pt: {
    title: 'Descobre a tua personagem ideal de Dungeons & Dragons!',
    button: 'Começar',
    footnote: 'Este quiz visa as mais recentes regras de Dungeons & Dragons e assume as seguintes opções de criação de personagem: todo o conteúdo do Player\'s Handbook 2024, todas as espécies do Mordenkainen Presents: Monsters of the Multiverse exceto as que foram revistas pelo Player\'s Handbook 2024 e todas as subclasses e espécies introduzidas pelo Valda’s Spire of Secrets: Player Pack conforme publicado pelo D&D Beyond.'
  },
  en: {
    title: 'Discover your ideal Dungeons & Dragons character!',
    button: 'Start',
    footnote: 'This quiz uses the latest Dungeons & Dragons rules and assumes the following character creation options: all content from the 2024 Player\'s Handbook, all species from Mordenkainen Presents: Monsters of the Multiverse except those revised by the 2024 Player\'s Handbook, and all subclasses and species introduced by Valda\u2019s Spire of Secrets: Player Pack as published by D&D Beyond.'
  }
};

const nameMap = {
  pt: {
    species: {
      'Aasimar':'Aasimar',
      'Dragonborn':'Draconato',
      'Black Dragonborn':'Draconato Negro',
      'Blue Dragonborn':'Draconato Azul',
      'Brass Dragonborn':'Draconato de Latão',
      'Bronze Dragonborn':'Draconato de Bronze',
      'Copper Dragonborn':'Draconato de Cobre',
      'Gold Dragonborn':'Draconato Ouro',
      'Green Dragonborn':'Draconato Verde',
      'Red Dragonborn':'Draconato Vermelho',
      'Silver Dragonborn':'Draconato de Prata',
      'White Dragonborn':'Draconato Branco',
      'Dwarf':'Anão',
      'Elf':'Elfo',
      'Drow Elf':'Elfo Drow',
      'High Elf':'Alto Elfo',
      'Wood Elf':'Elfo dos Bosques',
      'Gnome':'Gnomo',
      'Forest Gnome':'Gnomo da Floresta',
      'Rock Gnome':'Gnomo das Rochas',
      'Goliath':'Golias',
      'Cloud Goliath':'Golias das Nuvens',
      'Fire Goliath':'Golias do Fogo',
      'Frost Goliath':'Golias da Geada',
      'Hill Goliath':'Golias das Colinas',
      'Stone Goliath':'Golias de Pedra',
      'Storm Goliath':'Golias da Tempestade',
      'Halfling':'Halfling',
      'Human':'Humano',
      'Orc':'Orque',
      'Tiefling':'Tiefling',
      'Abyssal Tiefling':'Tiefling Abissal',
      'Chthonic Tiefling':'Tiefling Ctónico',
      'Infernal Tiefling':'Tiefling Infernal',
      'Aarakocra':'Aarakocra',
      'Bugbear':'Bicho-papão',
      'Centaur':'Centauro',
      'Changeling':'Changeling',
      'Firbolg':'Firbolg',
      'Githyanki':'Githyanki',
      'Githzerai':'Githzerai',
      'Goblin':'Duende',
      'Hobgoblin':'Hobgoblin',
      'Kobold':'Kobold',
      'Lizardfolk':'Lizardfolk',
      'Minotaur':'Minotauro',
      'Satyr':'Sátiro',
      'Tabaxi':'Tabaxi',
      'Triton':'Tritão',
      'Yuan-ti':'Yuan-ti',
      'Deep Gnome':'Gnomo das Profundezas',
      'Duergar':'Duergar',
      'Eladrin':'Eladrin',
      'Autumn Eladrin':'Eladrin Outonal',
      'Winter Eladrin':'Eladrin Invernal',
      'Spring Eladrin':'Eladrin Primaveril',
      'Summer Eladrin':'Eladrin Estival',
      'Fairy':'Fada',
      'Genasi':'Genasi',
      'Air Genasi':'Genasi do Ar',
      'Earth Genasi':'Genasi da Terra',
      'Fire Genasi':'Genasi do Fogo',
      'Water Genasi':'Genasi da Água',
      'Geppettin (Marionette)':'Geppettin Marioneta',
      'Geppettin (Plushie or Bisque)':'Geppettin de Peluche ou Porcelana',
      'Marionette Geppettin':'Geppettin Marioneta',
      'Bisque Geppettin':'Geppettin de Porcelana',
      'Plushie Geppettin':'Geppettin de Peluche',
      'Harengon':'Harengon',
      'Kenku':'Kenku',
      'Mandrake':'Mandrágora',
      'Spring Mandrake':'Mandrágora Primaveril',
      'Summer Mandrake':'Mandrágora Estival',
      'Autumn Mandrake':'Mandrágora Outonal',
      'Winter Mandrake':'Mandrágora Invernal',
      'Sea Elf':'Elfo do Mar',
      'Shadar-kai':'Shadar-kai',
      'Shifter':'Metamorfo',
      'Beasthide Shifter':'Metamorfo Encouraçado',
      'Longtooth Shifter':'Metamorfo Lupino',
      'Swiftstride Shifter':'Metamorfo Veloz',
      'Wildhunt Shifter':'Metamorfo Canídeo',
      'Tortle':'Tortle'
    },
    classes: {
      'Barbarian':'Bárbaro',
      'Bard':'Bardo',
      'Cleric':'Clérigo',
      'Druid':'Druida',
      'Fighter':'Guerreiro',
      'Monk':'Monge',
      'Paladin':'Paladino',
      'Ranger':'Patrulheiro',
      'Rogue':'Ladino',
      'Sorcerer':'Feiticeiro',
      'Warlock':'Bruxo',
      'Wizard':'Mago'
    },
    backgrounds: {
      'Acolyte':'Acólito',
      'Artisan':'Artesão',
      'Charlatan':'Charlatão',
      'Criminal':'Criminoso',
      'Entertainer':'Artista',
      'Farmer':'Camponês',
      'Guard':'Guarda',
      'Guide':'Guia',
      'Hermit':'Eremita',
      'Merchant':'Comerciante',
      'Noble':'Nobre',
      'Sage':'Estudioso',
      'Sailor':'Marinheiro',
      'Scribe':'Escrivão',
      'Soldier':'Soldado',
      'Wayfarer':'Errante'
    },
    subclasses: {
      'Path of the Berserker': 'do Caminho da Ira',
      'Path of the Wild Heart': 'do Caminho do Coração Selvagem',
      'Path of the World Tree': 'do Caminho da Árvore do Mundo',
      'Path of the Zealot': 'do Caminho do Fanático',
      'Path of the Muscle Wizard': 'do Caminho do Mago Musculado',
      'College of Dance': 'do Colégio da Dança',
      'College of Glamour': 'do Colégio do Deslumbre',
      'College of Lore': 'do Colégio do Conhecimento',
      'College of Valor': 'do Colégio da Bravura',
      'Life Domain': 'do Domínio da Vida',
      'Light Domain': 'do Domínio da Luz',
      'Trickery Domain': 'do Domínio da Trapaça',
      'War Domain': 'do Domínio da Guerra',
      'Circle of the Land': 'do Círculo da Terra',
      'Circle of the Moon': 'do Círculo da Lua',
      'Circle of the Sea': 'do Círculo do Mar',
      'Circle of Stars': 'do Círculo das Estrelas',
      'Champion': 'Campeão',
      'Battle Master': 'Mestre de Batalha',
      'Eldritch Knight': 'Místico',
      'Psi Warrior': 'Psiónico',
      Dungeoneer: 'Explorador de Masmorras',
      'Way of the Open Hand': 'da Técnica da Mão Aberta',
      'Way of Shadow': 'da Técnica da Sombra',
      'Way of the Elements': 'da Técnica dos Elementos',
      'Way of Mercy': 'da Técnica da Misericórdia',
      'Warrior of the Street': 'Lutador das Ruas',
      'Oath of Devotion': 'do Juramento da Devoção',
      'Oath of Glory': 'do Juramento da Glória',
      'Oath of the Ancients': 'do Juramento dos Ancestrais',
      'Oath of Vengeance': 'do Juramento da Vingança',
      'Oath of Revelry': 'do Juramento da Celebração',
      'Beast Master': 'Mestre das Feras',
      'Fey Wanderer': 'Viajante Feérico',
      'Gloom Stalker': 'Viajante das Sombras',
      'Hunter': 'Caçador',
      'Arachnoid Stalker': 'Predador Aracnídeo',
      'Arcane Trickster': 'Trapaceiro Arcano',
      'Assassin': 'Assassino',
      'Soulknife': 'da Lâmina Psíquica',
      Thief: 'Ladrão',
      'Aberrant Sorcery': 'da Magia Aberrante',
      'Clockwork Sorcery': 'da Magia Mecânica',
      'Draconic Sorcery': 'da Magia Dracónica',
      'Wild Magic': 'da Magia Caótica',
      'Archfey Patron': 'com Patrono Arqui-feérico',
      'Celestial Patron': 'com Patrono Celestial',
      'Fiend Patron': 'com Patrono Infernal',
      'Future You': 'com A Sua Versão Futura como Patrono',
      'Great Old One Patron': 'com Patrono Grande Ancião',
      Abjurer: 'Abjurador',
      Diviner: 'Divinador',
      Evoker: 'Evocador',
      Illusionist: 'Ilusionista'
    }
  },
  en: { species:{}, classes:{}, backgrounds:{}, subclasses:{} }
};
